version: "3.9"
services:
  db:
    image: postgres:16
    container_name: customer_service_app_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: (!2KvQSnQzWg)
      POSTGRES_DB: customer_service_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d customer_service_app"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
